name: FSP CRM Backend Development CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Development Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
        run: |
          curl 'https://api.telegram.org/bot6725176067:AAEDuyNZ8Hd_5H6mCqohV38648O7CpOEj3s/sendMessage?chat_id=-1002048118873&text=test'
          echo "${SSH_PRIVATE_KEY}" > ssh_key
          chmod 600 ssh_key

          mkdir -p ~/.ssh
#          cp ssh_key ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
#          ssh root@${{ secrets.HOST }}
#          rsync -avz -e "ssh -i ssh_key" --exclude='venv' --exclude='.git' ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/project
#          secure copy
#          set -e
          ssh -tt -i ssh_key root@${{ secrets.HOST }} << EOF
            cd /root/CRM_BACKEND/fsp-crm-backend
            git pull
            sudo systemctl restart cr_m.service
            sudo systemctl status cr_m.service
            curl 'https://api.telegram.org/bot6725176067:AAEDuyNZ8Hd_5H6mCqohV38648O7CpOEj3s/sendMessage?chat_id=-1002048118873&text=Succesful Deployed'
          EOF

               
               
               
#            source /home/venv/bin/activate
#            cd /home/fsp-crm-backend
#            pip install -r requirements.txt
#            python3 manage.py migrate
#            python3 manage.py collectstatic --noinput
#            sudo systemctl restart project.service
#            curl ...
#            echo "Deployment successful"
            
